from .admin import admin_labeler
from .tutor import tutor_labeler
from .client import client_labeler
from .module_1 import module_1_labeler
from .module_2 import module_2_labeler
from .module_3 import module_3_labeler
from .module_4 import module_4_labeler
from .module_5 import module_5_labeler
from .module_6 import module_6_labeler
from .module_7 import module_7_labeler
from .module_8 import module_8_labeler
